services:
  - type: worker
    name: novabot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: starter
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URL
        sync: false
      - key: OWNER_ID
        sync: false
